var annotated_dup =
[
    [ "MathUtils", "namespaceMathUtils.html", [
      [ "Ray", "structMathUtils_1_1Ray.html", "structMathUtils_1_1Ray" ]
    ] ],
    [ "Physics", "namespacePhysics.html", [
      [ "Bounding", "namespacePhysics_1_1Bounding.html", [
        [ "AABB", "classPhysics_1_1Bounding_1_1AABB.html", "classPhysics_1_1Bounding_1_1AABB" ],
        [ "BoxCollider", "classPhysics_1_1Bounding_1_1BoxCollider.html", "classPhysics_1_1Bounding_1_1BoxCollider" ]
      ] ],
      [ "PhysicsBody", "classPhysics_1_1PhysicsBody.html", "classPhysics_1_1PhysicsBody" ],
      [ "PhysicsSystem", "classPhysics_1_1PhysicsSystem.html", "classPhysics_1_1PhysicsSystem" ],
      [ "PointMass", "classPhysics_1_1PointMass.html", "classPhysics_1_1PointMass" ],
      [ "RigidBody", "classPhysics_1_1RigidBody.html", "classPhysics_1_1RigidBody" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Vertex >", "structstd_1_1hash_3_01Vertex_01_4.html", "structstd_1_1hash_3_01Vertex_01_4" ]
    ] ],
    [ "BatchKey", "structBatchKey.html", "structBatchKey" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "ComputeShader", "classComputeShader.html", "classComputeShader" ],
    [ "ContactInfo", "structContactInfo.html", "structContactInfo" ],
    [ "ForcesInspectorWidget", "classForcesInspectorWidget.html", "classForcesInspectorWidget" ],
    [ "Gizmo", "classGizmo.html", "classGizmo" ],
    [ "GlobalsInspectorWidget", "classGlobalsInspectorWidget.html", "classGlobalsInspectorWidget" ],
    [ "HierarchyWidget", "classHierarchyWidget.html", "classHierarchyWidget" ],
    [ "ICollider", "classICollider.html", "classICollider" ],
    [ "IDrawable", "classIDrawable.html", "classIDrawable" ],
    [ "IHandle", "classIHandle.html", "classIHandle" ],
    [ "IInspectorSection", "classIInspectorSection.html", "classIInspectorSection" ],
    [ "InspectorRow", "classInspectorRow.html", "classInspectorRow" ],
    [ "InspectorWidget", "classInspectorWidget.html", "classInspectorWidget" ],
    [ "InstanceData", "structInstanceData.html", "structInstanceData" ],
    [ "InterceptSolver", "classInterceptSolver.html", "classInterceptSolver" ],
    [ "IPickable", "classIPickable.html", "classIPickable" ],
    [ "ISolver", "classISolver.html", "classISolver" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "Mesh", "classMesh.html", "classMesh" ],
    [ "ObjectOptions", "structObjectOptions.html", "structObjectOptions" ],
    [ "ObjectSnapshot", "structObjectSnapshot.html", "structObjectSnapshot" ],
    [ "OneUnknownSolver", "classOneUnknownSolver.html", "classOneUnknownSolver" ],
    [ "OpenGLWindow", "classOpenGLWindow.html", "classOpenGLWindow" ],
    [ "PhysicsInspectorWidget", "classPhysicsInspectorWidget.html", "classPhysicsInspectorWidget" ],
    [ "PointMassOptions", "structPointMassOptions.html", "structPointMassOptions" ],
    [ "ProblemRouter", "classProblemRouter.html", "classProblemRouter" ],
    [ "RawInputFilter", "classRawInputFilter.html", "classRawInputFilter" ],
    [ "ResourceManager", "classResourceManager.html", "classResourceManager" ],
    [ "RigidBodyOptions", "structRigidBodyOptions.html", "structRigidBodyOptions" ],
    [ "RotateHandle", "classRotateHandle.html", "classRotateHandle" ],
    [ "ScalarWidget", "classScalarWidget.html", "classScalarWidget" ],
    [ "ScaleHandle", "classScaleHandle.html", "classScaleHandle" ],
    [ "Scene", "classScene.html", "classScene" ],
    [ "SceneManager", "classSceneManager.html", "classSceneManager" ],
    [ "SceneObject", "classSceneObject.html", "classSceneObject" ],
    [ "SceneSerializer", "classSceneSerializer.html", "classSceneSerializer" ],
    [ "Shader", "classShader.html", "classShader" ],
    [ "SimulationStopCondition", "structSimulationStopCondition.html", "structSimulationStopCondition" ],
    [ "SnapshotTableModel", "classSnapshotTableModel.html", "classSnapshotTableModel" ],
    [ "SolverDecision", "structSolverDecision.html", "structSolverDecision" ],
    [ "SolverDialog", "classSolverDialog.html", "classSolverDialog" ],
    [ "TransformInspectorWidget", "classTransformInspectorWidget.html", "classTransformInspectorWidget" ],
    [ "TranslateHandle", "classTranslateHandle.html", "classTranslateHandle" ],
    [ "UniformBuffer", "classUniformBuffer.html", "classUniformBuffer" ],
    [ "Vector3Widget", "classVector3Widget.html", "classVector3Widget" ],
    [ "VectorRootSolver", "classVectorRootSolver.html", "classVectorRootSolver" ],
    [ "Vertex", "structVertex.html", "structVertex" ]
];