var annotated_dup =
[
    [ "Math", "namespaceMath.html", [
      [ "HitResult", "namespaceMath.html#structMath_1_1HitResult", "namespaceMath_structMath_1_1HitResult_dup" ],
      [ "Ray", "namespaceMath.html#structMath_1_1Ray", "namespaceMath_structMath_1_1Ray_dup" ]
    ] ],
    [ "Physics", "namespacePhysics.html", [
      [ "Bounding", "namespacePhysics_1_1Bounding.html", [
        [ "AABB", "classPhysics_1_1Bounding_1_1AABB.html", "classPhysics_1_1Bounding_1_1AABB" ],
        [ "BoxCollider", "classPhysics_1_1Bounding_1_1BoxCollider.html", "classPhysics_1_1Bounding_1_1BoxCollider" ],
        [ "ContactInfo", "namespacePhysics_1_1Bounding.html#structPhysics_1_1Bounding_1_1ContactInfo", "namespacePhysics_1_1Bounding_structPhysics_1_1Bounding_1_1ContactInfo_dup" ],
        [ "ICollider", "classPhysics_1_1Bounding_1_1ICollider.html", "classPhysics_1_1Bounding_1_1ICollider" ]
      ] ],
      [ "PhysicsBody", "classPhysics_1_1PhysicsBody.html", "classPhysics_1_1PhysicsBody" ],
      [ "PhysicsSystem", "classPhysics_1_1PhysicsSystem.html", "classPhysics_1_1PhysicsSystem" ],
      [ "PointMass", "classPhysics_1_1PointMass.html", "classPhysics_1_1PointMass" ],
      [ "RigidBody", "classPhysics_1_1RigidBody.html", "classPhysics_1_1RigidBody" ]
    ] ],
    [ "Rendering", "namespaceRendering.html", [
      [ "InstanceData", "structRendering_1_1InstanceData.html", "structRendering_1_1InstanceData" ]
    ] ],
    [ "ScenePresets", "namespaceScenePresets.html", [
      [ "PresetDescriptor", "namespaceScenePresets.html#structScenePresets_1_1PresetDescriptor", "namespaceScenePresets_structScenePresets_1_1PresetDescriptor_dup" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Vertex >", "structstd_1_1hash_3_01Vertex_01_4.html", "structstd_1_1hash_3_01Vertex_01_4" ]
    ] ],
    [ "AppSettings", "classAppSettings.html", "classAppSettings" ],
    [ "BatchKey", "structBatchKey.html", "structBatchKey" ],
    [ "BVH", "classBVH.html", "classBVH" ],
    [ "BVHNode", "structBVHNode.html", "structBVHNode" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "CameraSettingsGroup", "structCameraSettingsGroup.html", "structCameraSettingsGroup" ],
    [ "CameraTab", "classCameraTab.html", "classCameraTab" ],
    [ "Colliders", "classColliders.html", "classColliders" ],
    [ "ComputeShader", "classComputeShader.html", "classComputeShader" ],
    [ "DebugSettings", "structDebugSettings.html", "structDebugSettings" ],
    [ "DebugTab", "classDebugTab.html", "classDebugTab" ],
    [ "Forces", "classForces.html", "classForces" ],
    [ "ForcesInspectorWidget", "classForcesInspectorWidget.html", "classForcesInspectorWidget" ],
    [ "FrameGraphCanvas", "classFrameGraphCanvas.html", "classFrameGraphCanvas" ],
    [ "FrameGraphPanel", "classFrameGraphPanel.html", "classFrameGraphPanel" ],
    [ "FrameGraphWidget", "classFrameGraphWidget.html", "classFrameGraphWidget" ],
    [ "Gizmo", "classGizmo.html", "classGizmo" ],
    [ "GlobalsInspectorWidget", "classGlobalsInspectorWidget.html", "classGlobalsInspectorWidget" ],
    [ "HierarchyWidget", "classHierarchyWidget.html", "classHierarchyWidget" ],
    [ "ICustomDrawable", "classICustomDrawable.html", "classICustomDrawable" ],
    [ "IDrawable", "classIDrawable.html", "classIDrawable" ],
    [ "IHandle", "classIHandle.html", "classIHandle" ],
    [ "IInspectorSection", "classIInspectorSection.html", "classIInspectorSection" ],
    [ "IInstancedDrawable", "classIInstancedDrawable.html", "classIInstancedDrawable" ],
    [ "InspectorRow", "classInspectorRow.html", "classInspectorRow" ],
    [ "InspectorWidget", "classInspectorWidget.html", "classInspectorWidget" ],
    [ "InterceptSolver", "classInterceptSolver.html", "classInterceptSolver" ],
    [ "IPickable", "classIPickable.html", "classIPickable" ],
    [ "ISettingsGroup", "classISettingsGroup.html", "classISettingsGroup" ],
    [ "ISettingsTab", "classISettingsTab.html", "classISettingsTab" ],
    [ "ISolver", "classISolver.html", "classISolver" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "Mesh", "classMesh.html", "classMesh" ],
    [ "NodeIndex", "structNodeIndex.html", "structNodeIndex" ],
    [ "ObjectOptions", "SceneObjectOptions_8h.html#structObjectOptions", "SceneObjectOptions_8h_structObjectOptions" ],
    [ "ObjectSnapshot", "PhysicsBody_8h.html#structObjectSnapshot", "PhysicsBody_8h_structObjectSnapshot" ],
    [ "Octant", "structOctant.html", "structOctant" ],
    [ "Octree", "classOctree.html", "classOctree" ],
    [ "OctreeNode", "structOctreeNode.html", "structOctreeNode" ],
    [ "OneUnknownSolver", "classOneUnknownSolver.html", "classOneUnknownSolver" ],
    [ "OpenGLWindow", "classOpenGLWindow.html", "classOpenGLWindow" ],
    [ "PathTraces", "classPathTraces.html", "classPathTraces" ],
    [ "PhysicsInspectorWidget", "classPhysicsInspectorWidget.html", "classPhysicsInspectorWidget" ],
    [ "PointMassOptions", "structPointMassOptions.html", "structPointMassOptions" ],
    [ "ProblemRouter", "classProblemRouter.html", "classProblemRouter" ],
    [ "RawInputFilter", "classRawInputFilter.html", "classRawInputFilter" ],
    [ "ResourceManager", "classResourceManager.html", "classResourceManager" ],
    [ "RigidBodyOptions", "structRigidBodyOptions.html", "structRigidBodyOptions" ],
    [ "RotateHandle", "classRotateHandle.html", "classRotateHandle" ],
    [ "ScalarWidget", "classScalarWidget.html", "classScalarWidget" ],
    [ "ScaleHandle", "classScaleHandle.html", "classScaleHandle" ],
    [ "Scene", "classScene.html", "classScene" ],
    [ "SceneManager", "classSceneManager.html", "classSceneManager" ],
    [ "SceneObject", "classSceneObject.html", "classSceneObject" ],
    [ "SceneSerializer", "classSceneSerializer.html", "classSceneSerializer" ],
    [ "SettingsDialog", "classSettingsDialog.html", "classSettingsDialog" ],
    [ "Shader", "classShader.html", "classShader" ],
    [ "SimulationStopCondition", "SceneManager_8h.html#structSimulationStopCondition", "SceneManager_8h_structSimulationStopCondition" ],
    [ "SnapshotTableModel", "classSnapshotTableModel.html", "classSnapshotTableModel" ],
    [ "SolverDecision", "ProblemRouter_8h.html#structSolverDecision", "ProblemRouter_8h_structSolverDecision" ],
    [ "SolverDialog", "classSolverDialog.html", "classSolverDialog" ],
    [ "ThermalInspectorWidget", "classThermalInspectorWidget.html", "classThermalInspectorWidget" ],
    [ "ThermalProperties", "ThermalProperties_8h.html#structThermalProperties", "ThermalProperties_8h_structThermalProperties" ],
    [ "TransformInspectorWidget", "classTransformInspectorWidget.html", "classTransformInspectorWidget" ],
    [ "TranslateHandle", "classTranslateHandle.html", "classTranslateHandle" ],
    [ "UniformBuffer", "classUniformBuffer.html", "classUniformBuffer" ],
    [ "Vector3Widget", "classVector3Widget.html", "classVector3Widget" ],
    [ "VectorRootSolver", "classVectorRootSolver.html", "classVectorRootSolver" ],
    [ "Vertex", "structVertex.html", "structVertex" ]
];